### ISSUE TITLE
double title on some texbox window(and some not working parts in the script in the new ubuntu update) 

### ISSUE THREAD

**Issue by Cealica** [dominichayesferen/Chicagofier#3] opened 2022-05-15 17:18 UTC
I used xubuntu 22.04 and so far everything went fine-ish (the script didn't install the epiphany but i just installed it by myself, the customize xfce panel checkbox can't be checked in the new version of xubuntu so i have to do manually do some stuff in order to get the 1:1 ratio ) and after the reboot the first thing i've noticed is this:
![help](https://user-images.githubusercontent.com/95364273/168485515-f1a22b56-eaf4-4c95-b06f-e12869ef4540.png)
is this normal or is it a new bug? or an old one, either way im looking forward to your response

**Comment by dominichayesferen** [comment] 2022-05-16 21:18
That's normal as the application does that, due to having a headerbar.

**Comment by dominichayesferen** [comment] 2022-05-16 21:20
Because it's technically not a bug in our vicinity, but rather just an 'issue' with Mousepad using a headerbar and gtk3-nocsd not getting rid of that headerbar's own title, just in case there's anything valuable there I'd suspect, I'm gonna close this as 'invalid'.

There's probably a switch somewhere in XFCE to defer headerbars in XFCE applications, but if there is someone'll probably have to add it with a merge request or something as I am too busy right now to boot up Xubuntu.

**Closed as completed** 2022-05-16 21:20 UTC
Labels: invalid

**Comment by Cealica** [comment] 2022-05-18 07:58
oh i see, thanks!
